apiVersion: apps/v1
kind: Deployment
metadata:
  name: loopback4-app
  namespace: default # Change this if needed
  labels:
    app: loopback4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loopback4
  template:
    metadata:
      labels:
        app: loopback4
    spec:
      containers:
      - name: loopback4
        image: your-docker-registry/loopback4-app:latest # Change to your actual image
        ports:
        - containerPort: 3000
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: loopback-secrets
              key: JWT_SECRET
        - name: SQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: loopback-secrets
              key: SQL_DATABASE
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: loopback-secrets
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: loopback-secrets
              key: SQL_PASSWORD
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: loopback4-service
  namespace: default
spec:
  selector:
    app: loopback4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP # Change to LoadBalancer if exposing externally
