apiVersion: v1
kind: Service
metadata:
  name: loopback4-service
  namespace: ${NAMESPACE}
spec:
  selector:
    app: loopback4
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
