apiVersion: v1
kind: Service
metadata:
  name: ${BACKEND_NAME}-service
  namespace: ${BACKEND_NAME}-namespace
  labels:
    app: ${BACKEND_NAME}-service
spec:
  selector:
    app: ${BACKEND_NAME}-container
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
  sessionAffinity: None
