blank_issues_enabled: true

contact_links:
  - name: LoopBack 4 Support
    url: https://selecro.cz
    about: Get help and report issues related to the LoopBack 4 backend.

templates:
  - name: Bug Report
    filename: bug_report.md
    about: Report a bug in the LoopBack 4 backend application.
    title: "[Bug]: "
    labels: [bug, backend]
    assignees:
      - selecro-team
  - name: Feature Request
    filename: feature_request.md
    about: Suggest a new feature for the LoopBack 4 backend.
    title: "[Feature]: "
    labels: [feature, backend]
